export const INTERNAL_CANARY_MAX_AUTHORIZATION_MS = 24 * 60 * 60 * 1000;
export const INTERNAL_CANARY_CONFIRMATION_PHRASE = "AUTORIZAR CANARY INTERNO";
export const RISK_ACCEPTANCE_CONFIRMATION_PHRASE = "ACEPTAR RIESGO PARA CANARY INTERNO";
