import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test,{after,before,beforeEach} from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { createSignatureDomainServices } from "../lib/signatures/domain/service.ts";
import { createSignatureDraftLifecycleService } from "../lib/signatures/draft-lifecycle.ts";
import { createSignatureAdminRepository } from "../lib/signatures/admin-repository.ts";
import { sha256SignatureValue } from "../lib/signatures/domain/crypto.ts";
import { signatureStatusLabel } from "../lib/signatures/admin-ux.ts";

const root=process.cwd();
const names=["0022_create_signature_foundation.sql","0023_extend_signature_signer_evidence.sql","0024_add_signature_delivery_governance.sql","0025_bind_signature_privacy_disclosure.sql","0026_preserve_signature_privacy_disclosure_text.sql","0027_add_signature_launch_governance.sql","0028_harden_signature_launch_governance.sql","0029_add_signature_governance_workflows.sql","0030_harden_signature_governance_workflow_immutability.sql","0031_add_signature_legal_holds.sql","0032_correct_signature_business_governance.sql","0033_harden_signature_preflight_authorization.sql","0034_add_signature_operational_hiding.sql","0035_productize_boriki_sign.sql","0036_allow_historical_governance_effective_dates.sql","0037_add_signature_style_evidence.sql","0038_add_signature_practical_fields.sql","0039_add_public_launch_readiness_scope.sql","0040_add_signature_operational_restore.sql","0041_add_signature_test_cleanup.sql","0042_expand_test_signature_cleanup.sql"];
const migrations=await Promise.all(names.map((name)=>readFile(path.join(root,"db/migrations",name),"utf8")));
const db=new PGlite();const executor=(source)=>({async unsafe(query,parameters=[]){return(await source.query(query,parameters)).rows;}});const database={...executor(db),begin:(callback)=>db.transaction((tx)=>callback(executor(tx)))};let adminId,domain;
before(async()=>{await db.exec(`CREATE TABLE admin_users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),username text UNIQUE NOT NULL);CREATE TABLE leads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text,last_activity_at timestamptz DEFAULT now(),merged_into_lead_id uuid);CREATE TABLE lead_groups(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text,status text DEFAULT 'new',updated_at timestamptz DEFAULT now());INSERT INTO admin_users(username)VALUES('phase2p-admin')`);for(const migration of migrations)await db.exec(migration);adminId=(await db.query(`SELECT id::text FROM admin_users LIMIT 1`)).rows[0].id;});
beforeEach(async()=>{await db.exec(`TRUNCATE signature_governance_events,signature_events,signature_field_values,signature_sessions,signature_delivery_intents,signature_signing_tokens,signature_fields,signature_participants,signature_document_versions,signature_documents CASCADE`);domain=createSignatureDomainServices({database,eventHmacKey:"phase2p-event-key-at-least-thirty-two-bytes",eventHmacKeyVersion:1,networkEvidenceHmacKey:"phase2p-network-key-at-least-thirty-two-bytes"});});after(()=>db.close());
async function draft(){const bytes=new Uint8Array([37,80,68,70]),hash=sha256SignatureValue(bytes),documentId=randomUUID();const created=await domain.createDraftWithVersion({documentId,title:"Phase 2P synthetic",documentType:"transaction_acknowledgment",createdByAdminId:adminId,expiresAt:new Date("2035-01-01"),filename:"phase2p.pdf",byteCount:bytes.length,pageCount:1,sourceSha256:hash,pageGeometryManifest:[{pageIndex:0,mediaBox:{x:0,y:0,width:612,height:792},cropBox:{x:0,y:0,width:612,height:792},rotation:0,userUnit:1}],documentCreatedIdempotencyKey:randomUUID(),versionCreatedIdempotencyKey:randomUUID()});return{...created,bytes,hash};}
function storage(created){const objects=new Map([[created.sourceR2Key,created.bytes]]);return{objects,async getSource(){return created.bytes},async deleteSourceIfExact(input){return objects.delete(input.key)},async putSource(input){objects.set(input.key,input.bytes);return"created"}};}

test("Spanish status mapping uses familiar operational language",()=>{assert.equal(signatureStatusLabel("draft"),"Borrador");assert.equal(signatureStatusLabel("partially_signed"),"Firmado parcialmente");assert.equal(signatureStatusLabel("voided"),"Cancelado");assert.equal(signatureStatusLabel("archived"),"Archivado");});

test("workflow removal hides evidence-bearing records without deleting source or changing lifecycle state",async()=>{const created=await draft(),store=storage(created),service=createSignatureDraftLifecycleService(database,store,()=>new Date("2032-06-01"));await domain.addParticipant({documentVersionId:created.documentVersionId,nameSnapshot:"Synthetic",emailSnapshot:"synthetic@example.test",role:"Comprador",actorAdminId:adminId,idempotencyKey:randomUUID()});await service.hideFromOperationalWorkflow({documentId:created.documentId,actorAdminId:adminId,reason:"Remove from daily workflow"});const [row]=await database.unsafe(`SELECT status,operationally_hidden_at IS NOT NULL hidden FROM signature_documents WHERE id=$1`,[created.documentId]);assert.deepEqual(row,{status:"draft",hidden:true});assert.equal(store.objects.size,1);assert.equal((await db.query(`SELECT count(*)::int count FROM signature_governance_events WHERE action='workflow_hidden'`)).rows[0].count,1);await assert.rejects(db.query(`UPDATE signature_documents SET operationally_hidden_reason='rewrite' WHERE id=$1`,[created.documentId]),/immutable/);});

test("operational restore preserves immutable hide evidence and restores visibility once",async()=>{const created=await draft(),store=storage(created),service=createSignatureDraftLifecycleService(database,store,()=>new Date("2032-06-01"));await domain.addParticipant({documentVersionId:created.documentVersionId,nameSnapshot:"Synthetic",emailSnapshot:"synthetic@example.test",role:"Comprador",actorAdminId:adminId,idempotencyKey:randomUUID()});await service.hideFromOperationalWorkflow({documentId:created.documentId,actorAdminId:adminId,reason:"Archive synthetic request"});const restored=await service.restoreToOperationalWorkflow({documentId:created.documentId,actorAdminId:adminId,reason:"Return to operational work"});assert.equal(restored.restored,true);const [row]=await database.unsafe(`SELECT status,operationally_hidden_at IS NOT NULL hidden,operationally_restored_at IS NOT NULL restored FROM signature_documents WHERE id=$1`,[created.documentId]);assert.deepEqual(row,{status:"draft",hidden:true,restored:true});assert.equal((await db.query(`SELECT count(*)::int count FROM signature_governance_events WHERE action='workflow_restored'`)).rows[0].count,1);await assert.rejects(service.restoreToOperationalWorkflow({documentId:created.documentId,actorAdminId:adminId,reason:"Second restore"}),/rejected/);});

test("removed draft recipient remains auditable but disappears from active preparation",async()=>{const created=await draft();const recipient=await domain.addParticipant({documentVersionId:created.documentVersionId,nameSnapshot:"Synthetic",emailSnapshot:"synthetic@example.test",role:"Comprador",actorAdminId:adminId,idempotencyKey:randomUUID()});await db.query(`UPDATE signature_participants SET removed_at=now(),removed_by_admin_id=$2,removal_reason='Synthetic removal' WHERE id=$1`,[recipient.participantId,adminId]);const detail=await createSignatureAdminRepository(database).detail(created.documentId);assert.equal(detail.participants.length,0);assert.equal((await db.query(`SELECT count(*)::int count FROM signature_participants`)).rows[0].count,1);await assert.rejects(db.query(`UPDATE signature_participants SET removal_reason='rewrite' WHERE id=$1`,[recipient.participantId]),/immutable/);});

test("Admin surfaces expose drawer, guided steps, safe removal and concise governance",async()=>{const [nav,directory,editor,detail,newDraft,newDraftPage,governance]=await Promise.all([readFile(path.join(root,"components/admin/AdminNav.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/page.tsx"),"utf8"),readFile(path.join(root,"components/admin/signatures/SignatureDraftEditor.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/[id]/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/nuevo/NewSignatureDraftForm.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/nuevo/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/gobernanza/page.tsx"),"utf8")]);assert.match(nav,/aria-modal="true"/);assert.match(nav,/Escape/);assert.match(nav,/document\.body\.style\.overflow/);assert.match(nav,/createPortal[\s\S]*document\.body/);assert.match(nav,/data-admin-drawer-overlay/);assert.match(nav,/fixed inset-y-0 left-0[\s\S]*h-dvh/);assert.match(directory,/Recientes/);assert.match(directory,/Archivados/);assert.match(directory,/Nuevo documento/);assert.match(editor,/Destinatarios/);assert.match(editor,/Eliminar solicitud/);assert.match(editor,/Ver estado y soporte/);assert.match(editor,/application\/x-borikipr-signature-field/);assert.match(editor,/detail\.participants\.some\([\s\S]*participant\.id === selectedParticipantId/);assert.match(newDraft,/disabled=\{busy \|\| !hydrated\}/);assert.doesNotMatch(newDraft,/min=\{new Date\(/);assert.match(newDraftPage,/minimumExpirationDate/);assert.match(detail,/Detalles avanzados/);assert.match(governance,/READINESS_LABELS[\s\S]*Listo[\s\S]*Bloqueado/);assert.match(governance,/Auditoría y referencia/);assert.doesNotMatch(governance,/Ver estado bilingüe/);assert.doesNotMatch(directory,/readinessHash|sourceSha256|document\.id/);});

test("Governance derives public launch and recovery state from the canonical server gate",async()=>{const [governance,layout]=await Promise.all([readFile(path.join(root,"app/admin/signatures/gobernanza/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/layout.tsx"),"utf8")]);assert.match(governance,/inspectProductionPublicLaunchGate/);assert.match(governance,/recoveryChecks/);assert.doesNotMatch(governance,/Falta una restauración real en rama\/base aislada/);assert.match(layout,/inspectProductionPublicLaunchGate/);assert.match(layout,/publicLaunchAllowed/);assert.doesNotMatch(layout,/Sujeta a validación/);});
