import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { buildTemplateBlueprint,templateSnapshotSha256 } from "../lib/signatures/productization.ts";

const root=process.cwd();
test("Phase 3A schema preserves routing, broker, template, correction and date-signed invariants",async()=>{const sql=await readFile(path.join(root,"db/migrations/0035_productize_boriki_sign.sql"),"utf8");assert.match(sql,/date_signed/);assert.match(sql,/signature_participants_one_broker_final_idx/);assert.match(sql,/configured final broker/);assert.match(sql,/signature_templates/);assert.match(sql,/corrects_document_id/);});
test("template blueprint removes identities and retains only roles, routing and fields",()=>{const blueprint=buildTemplateBlueprint({participants:[{id:"person-1",name:"Private Name",email:"private@example.test",role:"Comprador",routingOrder:1,isBrokerFinalSigner:false}],fields:[{id:"field-1",participantId:"person-1",fieldType:"signature",pageIndex:0,normalizedX:.1,normalizedY:.2,normalizedWidth:.3,normalizedHeight:.1,pageGeometryReference:{pageIndex:0},label:"Firma",required:true,tabOrder:1,validationLimits:{}}]});const body=JSON.stringify(blueprint);assert.doesNotMatch(body,/Private Name|private@example/);assert.match(body,/Comprador/);assert.match(templateSnapshotSha256(blueprint),/^[0-9a-f]{64}$/);});
test("daily signing surfaces expose documents, templates and settings without making Governance primary",async()=>{const [home,settings,templates,editor]=await Promise.all([readFile(path.join(root,"app/admin/signatures/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/configuracion/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/plantillas/page.tsx"),"utf8"),readFile(path.join(root,"components/admin/signatures/SignatureDraftEditor.tsx"),"utf8")]);assert.match(home,/Plantillas/);assert.match(home,/Configuración/);assert.doesNotMatch(home,/>Gobernanza</);assert.match(settings,/Corredora · firma final/);assert.match(templates,/Nunca guardan firmas, valores, tokens ni sesiones/);assert.match(editor,/Fecha de firma/);assert.match(editor,/Corredora · Firma final/);});
test("template redirects stay on the browser origin and canary access remains conjunctive",async()=>{const [instantiate,detail]=await Promise.all([readFile(path.join(root,"app/api/admin/signatures/templates/[id]/instantiate/route.ts"),"utf8"),readFile(path.join(root,"app/admin/signatures/[id]/page.tsx"),"utf8")]);assert.match(instantiate,/request\.headers\.get\("origin"\)/);assert.match(detail,/isInternalCanarySigningEnabled\(\)\s*&&\s*scoped/);assert.doesNotMatch(detail,/isInternalCanarySigningEnabled\(\)\s*\|\|\s*scoped/);});
