import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { buildTemplateBlueprint,templateSnapshotSha256 } from "../lib/signatures/productization.ts";

const root=process.cwd();
test("Phase 3A schema preserves routing, broker, template, correction and date-signed invariants",async()=>{const sql=await readFile(path.join(root,"db/migrations/0035_productize_boriki_sign.sql"),"utf8");assert.match(sql,/date_signed/);assert.match(sql,/signature_participants_one_broker_final_idx/);assert.match(sql,/configured final broker/);assert.match(sql,/signature_templates/);assert.match(sql,/corrects_document_id/);});
test("template blueprint removes identities and retains only roles, routing and fields",()=>{const blueprint=buildTemplateBlueprint({participants:[{id:"person-1",name:"Private Name",email:"private@example.test",role:"Comprador",routingOrder:1,isBrokerFinalSigner:false}],fields:[{id:"field-1",participantId:"person-1",fieldType:"signature",pageIndex:0,normalizedX:.1,normalizedY:.2,normalizedWidth:.3,normalizedHeight:.1,pageGeometryReference:{pageIndex:0},label:"Firma",required:true,tabOrder:1,validationLimits:{}}]});const body=JSON.stringify(blueprint);assert.doesNotMatch(body,/Private Name|private@example/);assert.match(body,/Comprador/);assert.match(templateSnapshotSha256(blueprint),/^[0-9a-f]{64}$/);});
test("template blueprint marks only explicitly selected non-broker roles optional",()=>{const detail={participants:[{id:"buyer-1",name:"A",email:"a@example.test",role:"Comprador 1",routingOrder:1,isBrokerFinalSigner:false},{id:"buyer-2",name:"B",email:"b@example.test",role:"Comprador 2",routingOrder:1,isBrokerFinalSigner:false},{id:"broker",name:"Broker",email:"broker@example.test",role:"Corredora · Firma final",routingOrder:2,isBrokerFinalSigner:true}],fields:[]};const blueprint=buildTemplateBlueprint(detail,{optionalParticipantIds:new Set(["buyer-2","broker"])});assert.equal(blueprint.roles[0].optional,false);assert.equal(blueprint.roles[1].optional,true);assert.equal(blueprint.roles[2].optional,false);});
test("daily signing surfaces expose documents, templates and settings without making Governance primary",async()=>{const [home,settings,templates,editor]=await Promise.all([readFile(path.join(root,"app/admin/signatures/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/configuracion/page.tsx"),"utf8"),readFile(path.join(root,"app/admin/signatures/plantillas/page.tsx"),"utf8"),readFile(path.join(root,"components/admin/signatures/SignatureDraftEditor.tsx"),"utf8")]);assert.match(home,/Plantillas/);assert.match(home,/Configuración/);assert.doesNotMatch(home,/>Gobernanza</);assert.match(settings,/Corredora · firma final/);assert.match(templates,/Nunca guardan firmas, valores, tokens ni sesiones/);assert.match(editor,/Fecha de firma/);assert.match(editor,/Corredora · Firma final/);});
test("template redirects stay on the browser origin and canary access remains conjunctive",async()=>{const [instantiate,detail]=await Promise.all([readFile(path.join(root,"app/api/admin/signatures/templates/[id]/instantiate/route.ts"),"utf8"),readFile(path.join(root,"app/admin/signatures/[id]/page.tsx"),"utf8")]);assert.match(instantiate,/request\.headers\.get\("origin"\)/);assert.match(instantiate,/blueprintRole\.optional&&!name&&!email/);assert.match(instantiate,/finalOrder=Math\.max/);assert.match(detail,/isProductionInternalCanaryCapabilityEnabled\(\)/);assert.match(detail,/internalCanaryEnabled&&scoped/);assert.doesNotMatch(detail,/internalCanaryEnabled\|\|scoped/);});
test("Phase 3B catalog keeps real identities out of reusable template blueprints",async()=>{const source=await readFile(path.join(root,"scripts/signatures/configure-phase3b-initial-product.ts"),"utf8");assert.match(source,/Hoja de Oferta/);assert.match(source,/Hoja Informativa de los Compradores/);assert.match(source,/Contrato de Opción de Compraventa/);assert.match(source,/example\.invalid/);assert.doesNotMatch(source,/cedricjsantiago@gmail|ericksonrealestatepr@gmail/i);});
test("template requests preserve an exact Puerto Rico expiration time",async()=>{const [route,page]=await Promise.all([readFile(path.join(root,"app/api/admin/signatures/templates/[id]/instantiate/route.ts"),"utf8"),readFile(path.join(root,"app/admin/signatures/plantillas/[id]/usar/page.tsx"),"utf8")]);assert.match(route,/\\d\{2\}:\\d\{2\}/);assert.match(route,/:00-04:00/);assert.match(route,/form\.get\("expiresAt"\)/);assert.match(page,/type="datetime-local"/);assert.match(page,/hora de Puerto Rico/);});
test("production delivery worker honors the scoped signer runtime, not only the public gate",async()=>{const route=await readFile(path.join(root,"app/api/cron/process-email-queue/route.ts"),"utf8");assert.match(route,/isSignerRuntimeEnabled\(\)/);assert.doesNotMatch(route,/isPublicSigningEnabled\(\)/);});
