"use client";
/* eslint-disable @next/next/no-img-element */

import { startTransition, useActionState, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import Link from "next/link";
import {
  addSignatureFieldAction, addSignatureParticipantAction, prepareSignatureSendAction,
  resendSignatureInvitationAction, removeSignatureFieldAction, updateSignatureFieldAction,
  updateSignatureParticipantAction, removeSignatureParticipantAction, removeSignatureRequestAction,
  type SignatureAdminActionState,
} from "@/app/admin/signatures/actions";
import SignatureStepProgress from "./SignatureStepProgress";
import type { SignatureDraftDetail } from "@/lib/signatures/admin-repository";
import type { SignatureSendReadiness } from "@/lib/signatures/send-readiness";
import type { SignaturePreflightResult } from "@/lib/signatures/preflight";

const INITIAL:SignatureAdminActionState={ok:false,message:""};
const COLORS=["#11518b","#8a5a00","#6b3fa0","#16704a","#a33a3a","#226e78","#704214","#565b66"];
const FIELD_LABELS={signature:"Firma",initials:"Iniciales",date:"Fecha",text:"Texto"} as const;
type FieldType=keyof typeof FIELD_LABELS; type Rect={x:number;y:number;width:number;height:number};
const READINESS_LABELS:Record<string,string>={
  document_not_draft:"El documento ya no está en borrador.",active_version_missing:"Falta el PDF activo.",source_pdf_incompatible:"El PDF no pasó la validación.",version_already_locked:"La versión ya está cerrada para cambios.",expiration_invalid:"Selecciona una fecha de expiración válida.",event_keys_unavailable:"La configuración de evidencia no está disponible.",public_signing_disabled:"La activación de firma permanece deshabilitada.",document_classification_approval_missing:"Este tipo de documento todavía no ha sido aprobado para firma electrónica.",approved_consent_missing:"Falta aprobar el consentimiento es-PR.",retention_policy_missing:"Falta configurar y activar la política de retención.",privacy_disclosure_missing:"Falta aprobar la divulgación de privacidad.",participant_count_invalid:"Añade al menos un destinatario.",participant_email_invalid:"Revisa los correos de los destinatarios.",field_count_invalid:"Añade los campos requeridos.",required_participant_field_missing:"Cada destinatario necesita al menos un campo requerido.",field_definition_hash_stale:"Los campos cambiaron y deben revisarse nuevamente.",
};

function Feedback({state}:{state:SignatureAdminActionState}){return state.message?<p aria-live="polite" className={`mt-2 text-sm ${state.ok?"text-green-700":"text-red-700"}`}>{state.message}</p>:null;}
function bounded(rect:Rect):Rect{const width=Math.min(Math.max(rect.width,.04),1),height=Math.min(Math.max(rect.height,.025),1);return{x:Math.min(Math.max(rect.x,0),1-width),y:Math.min(Math.max(rect.y,0),1-height),width,height};}
function appendFieldData(form:FormData,input:{documentId:string;participantId:string;fieldType:FieldType;pageIndex:number;rect:Rect;label?:string;required?:boolean;maxLength?:number;fieldId?:string}){
  form.set("documentId",input.documentId);if(input.fieldId)form.set("fieldId",input.fieldId);form.set("participantId",input.participantId);form.set("fieldType",input.fieldType);form.set("pageIndex",String(input.pageIndex));form.set("x",String(input.rect.x));form.set("y",String(input.rect.y));form.set("width",String(input.rect.width));form.set("height",String(input.rect.height));form.set("label",input.label??FIELD_LABELS[input.fieldType]);form.set("required",String(input.required??true));form.set("maxLength",String(input.maxLength??120));
}

function FieldOverlay({documentId,field,color}:{documentId:string;field:SignatureDraftDetail["fields"][number];color:string}){
  const [rect,setRect]=useState({x:field.normalizedX,y:field.normalizedY,width:field.normalizedWidth,height:field.normalizedHeight});
  const [state,action,pending]=useActionState(updateSignatureFieldAction,INITIAL);
  function persist(next:Rect){const form=new FormData();appendFieldData(form,{documentId,fieldId:field.id,participantId:field.participantId,fieldType:field.fieldType,pageIndex:field.pageIndex,rect:next,label:field.label,required:field.required,maxLength:field.validationLimits.maxLength});startTransition(()=>action(form));}
  function begin(event:ReactPointerEvent<HTMLButtonElement>,mode:"move"|"resize"){
    event.preventDefault();event.stopPropagation();const target=event.currentTarget,origin={x:event.clientX,y:event.clientY,rect};target.setPointerCapture(event.pointerId);
    const next=(pointer:PointerEvent)=>{const scale=Math.max(target.parentElement?.parentElement?.getBoundingClientRect().width??1,1),dx=(pointer.clientX-origin.x)/scale,dy=(pointer.clientY-origin.y)/scale;return bounded(mode==="move"?{...origin.rect,x:origin.rect.x+dx,y:origin.rect.y+dy}:{...origin.rect,width:origin.rect.width+dx,height:origin.rect.height+dy});};
    function move(pointer:PointerEvent){setRect(next(pointer));} function end(pointer:PointerEvent){target.removeEventListener("pointermove",move);target.removeEventListener("pointerup",end);const value=next(pointer);setRect(value);persist(value);}
    target.addEventListener("pointermove",move);target.addEventListener("pointerup",end);
  }
  function keyboard(event:React.KeyboardEvent<HTMLButtonElement>){const step=event.shiftKey?.01:.002,delta=event.key==="ArrowLeft"?[-step,0]:event.key==="ArrowRight"?[step,0]:event.key==="ArrowUp"?[0,-step]:event.key==="ArrowDown"?[0,step]:null;if(!delta)return;event.preventDefault();const next=bounded({...rect,x:rect.x+delta[0],y:rect.y+delta[1]});setRect(next);persist(next);}
  return <div className="absolute touch-none" style={{left:`${rect.x*100}%`,top:`${rect.y*100}%`,width:`${rect.width*100}%`,height:`${rect.height*100}%`,zIndex:10}}><button aria-label={`Mover campo ${field.label}`} className="flex h-full w-full touch-none cursor-move items-center justify-center overflow-hidden border-2 bg-white/85 px-1 text-xs font-semibold shadow focus:ring-4 focus:ring-[#d4af37]/60" disabled={pending} onKeyDown={keyboard} onPointerDown={(event)=>begin(event,"move")} style={{borderColor:color,color}} type="button">{FIELD_LABELS[field.fieldType]}</button><button aria-label={`Redimensionar campo ${field.label}`} className="absolute -bottom-2 -right-2 h-6 w-6 touch-none rounded-md border-2 border-white shadow focus:ring-2 focus:ring-[#d4af37]" onPointerDown={(event)=>begin(event,"resize")} style={{backgroundColor:color}} type="button"/><span className="sr-only" aria-live="polite">{state.message}</span></div>;
}

export default function SignatureDraftEditor({detail,readiness,preflight,activationMode}:{detail:SignatureDraftDetail;readiness:SignatureSendReadiness;preflight:SignaturePreflightResult;activationMode:"public"|"internal_canary"|"disabled"}){
  const editable=detail.status==="draft"&&!detail.version.locked;
  const [step,setStep]=useState(editable?(detail.participants.length?3:2):4);const [pageIndex,setPageIndex]=useState(0);const [zoom,setZoom]=useState(1);const [selectedParticipantId,setParticipantId]=useState(detail.participants[0]?.id??"");
  const [participantState,participantAction,participantPending]=useActionState(addSignatureParticipantAction,INITIAL);const [fieldState,fieldAction,fieldPending]=useActionState(addSignatureFieldAction,INITIAL);const [sendState,sendAction,sendPending]=useActionState(prepareSignatureSendAction,INITIAL);const [,resendAction,resendPending]=useActionState(resendSignatureInvitationAction,INITIAL);const [removeState,removeAction,removePending]=useActionState(removeSignatureRequestAction,INITIAL);const canvasRef=useRef<HTMLDivElement>(null);
  const participantId=detail.participants.some((participant)=>participant.id===selectedParticipantId)?selectedParticipantId:detail.participants[0]?.id??"";
  function createField(fieldType:FieldType,rect:Rect){if(!participantId)return;const form=new FormData();appendFieldData(form,{documentId:detail.id,participantId,fieldType,pageIndex,rect:bounded(rect)});startTransition(()=>fieldAction(form));}
  function drop(event:React.DragEvent<HTMLDivElement>){event.preventDefault();const type=event.dataTransfer.getData("application/x-borikipr-signature-field") as FieldType;if(!FIELD_LABELS[type]||!canvasRef.current)return;const b=canvasRef.current.getBoundingClientRect(),width=type==="initials"||type==="date"?.18:.3;createField(type,{x:(event.clientX-b.left)/b.width-width/2,y:(event.clientY-b.top)/b.height-.035,width,height:.07});}
  const colors=new Map(detail.participants.map((p,i)=>[p.id,COLORS[i%COLORS.length]]));const pageFields=detail.fields.filter((f)=>f.pageIndex===pageIndex);const geometry=detail.version.pageGeometry[pageIndex];const rotated=geometry?.rotation===90||geometry?.rotation===270;const width=rotated?geometry?.cropBox.height:geometry?.cropBox.width,height=rotated?geometry?.cropBox.width:geometry?.cropBox.height;
  const required=detail.fields.filter((field)=>field.required).length,likelyInert=detail.status==="draft"&&detail.participants.length===0&&detail.fields.length===0;

  return <div className="signature-editor min-w-0 space-y-4"><SignatureStepProgress current={step}/>
    <div className="flex gap-2 overflow-x-auto pb-1" aria-label="Cambiar paso">{[2,3,4,5].map((number)=><button key={number} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${step===number?"bg-[#0d1b2a] text-white":"border bg-white"}`} onClick={()=>setStep(number)} type="button">{number===2?"Destinatarios":number===3?"Campos":number===4?"Revisar":"Enviar"}</button>)}</div>

    {step===2&&<section className="surface-card p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-xl font-semibold">2. Destinatarios</h2><p className="mt-1 text-sm text-slate-600">Añade quién debe firmar. El orden es solo de visualización y referencia; no activa una secuencia estricta.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-700">{detail.participants.length}/8</span></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{detail.participants.map((participant,index)=><RecipientCard key={participant.id} detail={detail} participant={participant} color={COLORS[index%COLORS.length]} resendAction={resendAction} resendPending={resendPending}/>)}</div>
      {editable&&<form action={participantAction} className="mt-6 grid gap-4 rounded-2xl border bg-slate-50 p-4 sm:grid-cols-2"><h3 className="text-lg font-semibold sm:col-span-2">Añadir destinatario</h3><label><span className="text-sm font-semibold">Nombre</span><input className="mt-1 w-full rounded-lg border px-3 py-3" name="name" required/></label><label><span className="text-sm font-semibold">Correo</span><input className="mt-1 w-full rounded-lg border px-3 py-3" name="email" type="email" required/></label><label><span className="text-sm font-semibold">Rol</span><input className="mt-1 w-full rounded-lg border px-3 py-3" name="role" placeholder="Comprador, Vendedor, Arrendador…" required/></label><label><span className="text-sm font-semibold">Orden de visualización (opcional)</span><input className="mt-1 w-full rounded-lg border px-3 py-3" name="routingOrder" type="number" min={1} max={8}/></label><input name="documentId" type="hidden" value={detail.id}/><button className="btn-primary sm:col-span-2 sm:justify-self-start" disabled={participantPending||detail.participants.length>=8} type="submit">Añadir destinatario</button><div className="sm:col-span-2"><Feedback state={participantState}/></div></form>}
    </section>}

    {step===3&&<section className="grid min-w-0 gap-5 xl:grid-cols-[250px_minmax(0,1fr)_300px]"><aside className="surface-card order-2 p-4 xl:order-1"><h2 className="text-lg font-semibold">Campos</h2><label className="mt-4 block text-sm font-semibold">Asignar a<select className="mt-1 w-full rounded-lg border px-3 py-2" value={participantId} onChange={(event)=>setParticipantId(event.target.value)}><option value="">Añade un destinatario</option>{detail.participants.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="mt-4 grid grid-cols-2 gap-2 xl:grid-cols-1">{(Object.keys(FIELD_LABELS) as FieldType[]).map((type)=><button className="min-h-11 rounded-xl border border-[#0d1b2a] bg-white px-3 py-2 text-sm font-semibold disabled:opacity-50" disabled={!editable||!participantId||fieldPending} draggable onClick={()=>createField(type,{x:.35,y:.45,width:type==="initials"||type==="date"?.18:.3,height:.07})} onDragStart={(e)=>e.dataTransfer.setData("application/x-borikipr-signature-field",type)} key={type} type="button">+ {FIELD_LABELS[type]}</button>)}</div><Feedback state={fieldState}/></aside>
      <div className="surface-card order-1 min-w-0 p-3 sm:p-5 xl:order-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">3. Coloca los campos</h2><p className="text-sm text-slate-600">Toca para añadir o arrastra en escritorio.</p></div><div className="flex items-center gap-2"><button className="btn-secondary" disabled={pageIndex===0} onClick={()=>setPageIndex((v)=>v-1)} type="button">Anterior</button><label className="text-sm font-semibold"><span className="sr-only">Página</span><select className="rounded-lg border px-2 py-2" value={pageIndex} onChange={(e)=>setPageIndex(Number(e.target.value))}>{Array.from({length:detail.version.pageCount},(_,i)=><option key={i} value={i}>Página {i+1}</option>)}</select></label><button className="btn-secondary" disabled={pageIndex+1>=detail.version.pageCount} onClick={()=>setPageIndex((v)=>v+1)} type="button">Siguiente</button></div></div>
        <div className="mt-3 flex justify-end"><label className="text-sm font-semibold">Zoom <select className="ml-2 rounded-lg border px-2 py-2" value={zoom} onChange={(e)=>setZoom(Number(e.target.value))}><option value={.75}>75%</option><option value={1}>100%</option><option value={1.25}>125%</option><option value={1.5}>150%</option></select></label></div>
        <div className="mt-4 max-h-[72vh] overflow-auto overscroll-contain rounded-xl border bg-slate-200 p-2"><div className="mx-auto origin-top" style={{width:`${zoom*100}%`,maxWidth:`${zoom*900}px`}}><div ref={canvasRef} aria-label={`Página ${pageIndex+1} del PDF`} className="relative w-full bg-white shadow" onDragOver={(e)=>e.preventDefault()} onDrop={drop} style={{aspectRatio:`${width??612}/${height??792}`}}><img alt={`Vista previa de la página ${pageIndex+1}`} className="h-full w-full object-contain" draggable={false} src={`/admin/signatures/${detail.id}/pages/${pageIndex}`}/>{pageFields.map((field)=><FieldOverlay key={field.id} documentId={detail.id} field={field} color={colors.get(field.participantId)??COLORS[0]}/>)}</div></div></div>
      </div><aside className="surface-card order-3 p-4"><h2 className="text-lg font-semibold">Campos añadidos ({detail.fields.length}/100)</h2><div className="mt-4 space-y-3">{detail.fields.map((field)=><FieldSettings key={field.id} detail={detail} field={field} editable={editable}/>)}{!detail.fields.length&&<p className="text-sm text-slate-500">Aún no hay campos.</p>}</div></aside></section>}

    {step===4&&<section className="grid gap-5 lg:grid-cols-2"><div className="surface-card p-5"><h2 className="text-xl font-semibold">4. Revisa antes de enviar</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Summary label="Documento" value={`${detail.title} · ${detail.version.pageCount} páginas`}/><Summary label="Expiración" value={detail.expiresAt?new Date(detail.expiresAt).toLocaleDateString("es-PR"):"Pendiente"}/><Summary label="Destinatarios" value={`${detail.participants.length} añadidos`}/><Summary label="Campos" value={`${detail.fields.length} totales · ${required} requeridos`}/><Summary label="Idioma" value="Español (Puerto Rico)"/><Summary label="Estado" value={readiness.eligible?"Listo":"Bloqueado"}/></dl></div><ReadinessCard readiness={readiness} preflight={preflight}/></section>}

    {step===5&&<section className="grid gap-5 lg:grid-cols-2"><div className="surface-card p-5"><h2 className="text-xl font-semibold">5. Enviar para firma</h2><p className={`mt-3 rounded-xl border p-3 text-sm font-semibold ${activationMode==="internal_canary"?"border-amber-300 bg-amber-50 text-amber-900":activationMode==="public"?"border-red-300 bg-red-50 text-red-900":"border-slate-300 bg-slate-50 text-slate-700"}`}>{activationMode==="internal_canary"?"CANARY INTERNO — prueba controlada, no envío público":activationMode==="public"?"ENVÍO A CLIENTE":"Firma desactivada"}</p><form action={sendAction} className="mt-4 grid gap-3"><input name="documentId" type="hidden" value={detail.id}/><input name="documentType" type="hidden" value={detail.documentType}/><p className="text-sm text-slate-600">{detail.title} · {detail.participants.length} destinatarios · es-PR · expira {detail.expiresAt?new Date(detail.expiresAt).toLocaleDateString("es-PR"):"sin fecha"}</p><label className="flex items-start gap-3 text-sm"><input className="mt-1" name="sendAcknowledged" type="checkbox" value="true" required/><span>Revisé el documento, destinatarios, campos, idioma y expiración.</span></label><label className="text-sm font-semibold">Escribe <code>{activationMode==="public"?"CONFIRMAR ENVIO PUBLICO":"CONFIRMAR ENVIO CANARY INTERNO"}</code><input className="mt-1 w-full rounded-lg border px-3 py-3 font-normal" name="sendConfirmationPhrase" required/></label><button className="btn-primary w-full disabled:opacity-60" disabled={sendPending||!readiness.eligible||activationMode==="disabled"} type="submit">{readiness.eligible&&activationMode!=="disabled"?"Enviar para firma":"Envío bloqueado"}</button><Feedback state={sendState}/></form></div><ReadinessCard readiness={readiness} preflight={preflight}/></section>}

    <section className="surface-card border border-red-200 p-5"><details><summary className="cursor-pointer font-semibold text-red-800">Eliminar solicitud</summary><p className="mt-3 text-sm text-slate-600">Borikí decidirá el tratamiento seguro. Si existe actividad, la solicitud saldrá de tu lista activa pero la evidencia necesaria permanecerá protegida.</p><form action={removeAction} className="mt-4 grid gap-3"><input name="documentId" type="hidden" value={detail.id}/><label className="text-sm font-semibold">Razón<input className="mt-1 w-full rounded-lg border px-3 py-3 font-normal" name="reason" maxLength={500} required/></label>{likelyInert&&<label className="text-sm font-semibold">Escribe <code>ELIMINAR BORRADOR</code><input className="mt-1 w-full rounded-lg border px-3 py-3 font-normal" name="confirmationPhrase" required/></label>}<button className="rounded-lg border border-red-300 px-4 py-3 font-semibold text-red-800" disabled={removePending} type="submit">{likelyInert?"Eliminar este borrador":"Quitar de solicitudes activas"}</button><Feedback state={removeState}/></form></details></section>

    <div className="sticky bottom-0 z-30 flex items-center justify-between gap-3 border-t bg-white/95 px-3 py-3 shadow-[0_-8px_30px_rgba(0,0,0,.08)] backdrop-blur" style={{paddingBottom:"max(.75rem,env(safe-area-inset-bottom))"}}><button className="btn-secondary" disabled={step<=2} onClick={()=>setStep((value)=>Math.max(2,value-1))} type="button">Atrás</button><span className="text-sm font-semibold">Paso {step} de 5</span><button className="btn-primary" disabled={step>=5||(step===2&&!detail.participants.length)} onClick={()=>setStep((value)=>Math.min(5,value+1))} type="button">{step===4?"Revisar envío":"Siguiente"}</button></div>
  </div>;
}

function Summary({label,value}:{label:string;value:string}){return <div><dt className="text-sm font-semibold text-slate-600">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
function ReadinessCard({readiness,preflight}:{readiness:SignatureSendReadiness;preflight:SignaturePreflightResult}){return <section className="surface-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Configuración para enviar</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${readiness.eligible?"bg-green-100 text-green-800":"bg-red-100 text-red-800"}`}>{readiness.eligible?"LISTO":"BLOQUEADO"}</span></div>{!readiness.eligible&&<><p className="mt-3 text-sm text-slate-600">Falta configuración para enviar este documento.</p><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{readiness.reasons.map((reason)=><li key={reason}>{READINESS_LABELS[reason]??"Hay un control pendiente que requiere revisión."}</li>)}</ul><Link className="mt-4 inline-flex font-semibold text-[#11518b] hover:underline" href="/admin/signatures/gobernanza">Ir a Gobernanza</Link></>}<details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Detalles avanzados</summary><p className="mt-2 break-all font-mono text-xs text-slate-500">Readiness SHA-256: {preflight.readinessHash}</p></details></section>}

function RecipientCard({detail,participant,color,resendAction,resendPending}:{detail:SignatureDraftDetail;participant:SignatureDraftDetail["participants"][number];color:string;resendAction:(payload:FormData)=>void;resendPending:boolean}){
  const [editing,setEditing]=useState(false);const [updateState,updateAction,updatePending]=useActionState(updateSignatureParticipantAction,INITIAL);const [removeState,removeAction,removePending]=useActionState(removeSignatureParticipantAction,INITIAL);const editable=detail.status==="draft"&&!detail.version.locked;
  return <article className="rounded-2xl border bg-white p-4" style={{borderLeftColor:color,borderLeftWidth:5}}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold">{participant.name}</h3><p className="break-all text-sm text-slate-600">{participant.email}</p><p className="mt-1 text-sm">{participant.role}{participant.routingOrder?` · Orden ${participant.routingOrder}`:""}</p></div>{editable&&<button className="text-sm font-semibold text-[#11518b]" onClick={()=>setEditing((value)=>!value)} type="button">{editing?"Cerrar":"Editar"}</button>}</div>
    {editing&&<form action={updateAction} className="mt-4 grid gap-3"><input name="documentId" type="hidden" value={detail.id}/><input name="participantId" type="hidden" value={participant.id}/><label className="text-sm font-semibold">Nombre<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="name" defaultValue={participant.name} required/></label><label className="text-sm font-semibold">Correo<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="email" defaultValue={participant.email} type="email" required/></label><label className="text-sm font-semibold">Rol<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="role" defaultValue={participant.role} required/></label><label className="text-sm font-semibold">Orden de visualización<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="routingOrder" defaultValue={participant.routingOrder??""} type="number" min={1} max={8}/></label><button className="btn-secondary" disabled={updatePending} type="submit">Guardar</button><Feedback state={updateState}/></form>}
    {editable&&<form action={removeAction} className="mt-3"><input name="documentId" type="hidden" value={detail.id}/><input name="participantId" type="hidden" value={participant.id}/><input name="reason" type="hidden" value="Eliminado por el operador durante la preparación"/><button className="text-sm font-semibold text-red-700" disabled={removePending} type="submit">Eliminar destinatario</button><Feedback state={removeState}/></form>}
    {["invited","viewed","consented"].includes(participant.status)&&<form action={resendAction} className="mt-3"><input name="documentId" type="hidden" value={detail.id}/><input name="participantId" type="hidden" value={participant.id}/><button className="text-sm font-semibold text-[#11518b]" disabled={resendPending} type="submit">Reenviar invitación</button></form>}
  </article>;
}

function FieldSettings({detail,field,editable}:{detail:SignatureDraftDetail;field:SignatureDraftDetail["fields"][number];editable:boolean}){const [updateState,updateAction,updatePending]=useActionState(updateSignatureFieldAction,INITIAL);const [removeState,removeAction,removePending]=useActionState(removeSignatureFieldAction,INITIAL);return <div className="rounded-xl border p-3"><form action={updateAction} className="space-y-2"><input name="documentId" type="hidden" value={detail.id}/><input name="fieldId" type="hidden" value={field.id}/><input name="fieldType" type="hidden" value={field.fieldType}/><input name="pageIndex" type="hidden" value={field.pageIndex}/><input name="x" type="hidden" value={field.normalizedX}/><input name="y" type="hidden" value={field.normalizedY}/><input name="width" type="hidden" value={field.normalizedWidth}/><input name="height" type="hidden" value={field.normalizedHeight}/><label className="block text-xs font-semibold">Etiqueta<input className="mt-1 w-full rounded-lg border px-2 py-2 text-sm" name="label" defaultValue={field.label}/></label><label className="block text-xs font-semibold">Destinatario<select className="mt-1 w-full rounded-lg border px-2 py-2 text-sm" name="participantId" defaultValue={field.participantId}>{detail.participants.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input name="required" type="hidden" value="false"/><input name="required" type="checkbox" value="true" defaultChecked={field.required}/> Requerido</label>{field.fieldType==="text"&&<input name="maxLength" type="hidden" value={field.validationLimits.maxLength??120}/>}<button className="text-sm font-semibold text-[#11518b]" disabled={!editable||updatePending} type="submit">Guardar</button><Feedback state={updateState}/></form><form action={removeAction} className="mt-2"><input name="documentId" type="hidden" value={detail.id}/><input name="fieldId" type="hidden" value={field.id}/><button className="text-sm font-semibold text-red-700" disabled={!editable||removePending} type="submit">Eliminar campo</button><Feedback state={removeState}/></form></div>}
