"use client";
import { useActionState } from "react";
import { correctSignatureRequestAction,duplicateSignatureRequestAction,removeSignatureRequestAction,voidSignatureDocumentAction,type SignatureAdminActionState } from "@/app/admin/signatures/actions";
const INITIAL:SignatureAdminActionState={ok:false,message:""};
function Result({state}:{state:SignatureAdminActionState}){return state.message?<p className={`text-sm ${state.ok?"text-emerald-700":"text-red-700"}`} aria-live="polite">{state.message}</p>:null;}
export default function SignatureDocumentActions({documentId,title,status}:{documentId:string;title:string;status:string}){
  const [duplicateState,duplicate,duplicatePending]=useActionState(duplicateSignatureRequestAction,INITIAL);const [correctState,correct,correctPending]=useActionState(correctSignatureRequestAction,INITIAL);const [voidState,voidAction,voidPending]=useActionState(voidSignatureDocumentAction,INITIAL);const [archiveState,archive,archivePending]=useActionState(removeSignatureRequestAction,INITIAL);const active=["sent","viewed","partially_signed"].includes(status);if(status==="archived")return null;
  return <details className="surface-card p-4"><summary className="cursor-pointer font-semibold">Más acciones</summary><div className="mt-4 grid gap-5 lg:grid-cols-2">
    <form action={duplicate} className="grid gap-2 rounded-xl border p-4"><h3 className="font-semibold">Duplicar</h3><p className="text-sm text-slate-600">Copia PDF, roles, campos y ruta; nunca firmas, valores, tokens ni sesiones.</p><input name="documentId" type="hidden" value={documentId}/><label className="text-sm font-semibold">Título<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="title" defaultValue={`Copia de ${title}`} required/></label><label className="text-sm font-semibold">Expira<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="expiresOn" type="date" required/></label><button className="btn-secondary justify-self-start" disabled={duplicatePending}>Duplicar solicitud</button><Result state={duplicateState}/></form>
    {active&&<form action={correct} className="grid gap-2 rounded-xl border p-4"><h3 className="font-semibold">Preparar corrección</h3><p className="text-sm text-slate-600">Crea un borrador vinculado. La original conserva su evidencia y debe anularse explícitamente antes de enviar la corrección.</p><input name="documentId" type="hidden" value={documentId}/><input name="title" type="hidden" value={`Corrección — ${title}`}/><label className="text-sm font-semibold">Expira<input className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="expiresOn" type="date" required/></label><button className="btn-secondary justify-self-start" disabled={correctPending}>Preparar corrección</button><Result state={correctState}/></form>}
    {active&&<form action={voidAction} className="grid gap-2 rounded-xl border border-red-200 p-4"><h3 className="font-semibold text-red-800">Cancelar solicitud</h3><p className="text-sm text-slate-600">Anula accesos pendientes de forma irreversible y conserva la evidencia.</p><input name="documentId" type="hidden" value={documentId}/><label className="text-sm font-semibold">Razón<textarea className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="reason" required/></label><button className="justify-self-start rounded-lg border border-red-300 px-4 py-2 font-semibold text-red-800" disabled={voidPending}>Cancelar</button><Result state={voidState}/></form>}
    {status!=="draft"&&<form action={archive} className="grid gap-2 rounded-xl border p-4"><h3 className="font-semibold">Archivar</h3><p className="text-sm text-slate-600">Quita la solicitud de la operación diaria sin borrar evidencia.</p><input name="documentId" type="hidden" value={documentId}/><label className="text-sm font-semibold">Razón<textarea className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" name="reason" required/></label><button className="btn-secondary justify-self-start" disabled={archivePending}>Archivar</button><Result state={archiveState}/></form>}
  </div></details>;
}
