import Link from "next/link";
import { randomUUID } from "node:crypto";
import { notFound, redirect } from "next/navigation";
import { CalendarClock, FileText, MessageSquareText, UsersRound } from "lucide-react";
import { AdminPageHeader, AdminPageShell } from "@/components/admin/AdminPageShell";
import { LeadDocumentCard } from "@/components/admin/LeadDocumentCard";
import { LeadInteractionCard } from "@/components/admin/LeadInteractionCard";
import { getAdminSessionUser } from "@/lib/admin/auth";
import { getLeadMergeHistory } from "@/lib/admin/queries/lead-identity-management";
import {
  LEAD_GROUP_ROLE_LABELS, LEAD_GROUP_STATUS_LABELS,
  getLeadGroupDetail, searchLeadGroupCandidates,
} from "@/lib/admin/queries/lead-groups";
import {
  addLeadGroupMemberAction, addLeadGroupNoteAction, changeLeadGroupPrimaryContactAction,
  removeLeadGroupMemberAction, updateLeadGroupAction, updateLeadGroupMemberRoleAction,
} from "@/app/admin/lead-groups/actions";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("es-PR", { timeZone: "America/Puerto_Rico", dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Sin fecha"; }
function localValue(value: string | null) { if (!value) return ""; const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Puerto_Rico", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value)); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? ""; return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`; }

function eventCopy(type: string, data: Record<string, unknown>, names: Map<string, string>) {
  const name = names.get(String(data.leadId ?? data.newLeadId ?? ""));
  if (type === "group_created") return `${[...names.values()].join(" y ")} fueron agrupadas en un caso compartido.`;
  if (type === "member_added") return `${name ?? "Una persona"} se añadió al caso.`;
  if (type === "member_removed") return `${name ?? "Una persona"} se removió del caso.`;
  if (type === "member_role_changed") return `Se actualizó la función de ${name ?? "una persona"}.`;
  if (type === "primary_contact_changed") return `${name ?? "Una persona"} quedó como contacto principal.`;
  if (type === "status_changed") return `Estado del caso cambiado a ${LEAD_GROUP_STATUS_LABELS[String(data.newStatus) as keyof typeof LEAD_GROUP_STATUS_LABELS] ?? String(data.newStatus)}.`;
  if (type === "follow_up_changed") return data.newAt ? `Seguimiento del caso programado para ${formatDate(String(data.newAt))}.` : "Se eliminó el seguimiento del caso.";
  if (type === "note_added") return "Se añadió una nota compartida.";
  if (type === "contacted") return "Contacto del caso registrado.";
  return "Actividad del caso.";
}
function memberManagementCopy(type: string, name: string) {
  if (type === "document_accessed") return `Se consultó un documento de ${name}.`;
  if (type === "status_changed") return `Se actualizó el estado individual de ${name}.`;
  if (type === "follow_up_changed") return `Se actualizó el seguimiento individual de ${name}.`;
  if (type === "relationship_created") return `Se confirmó una relación de ${name}.`;
  if (type === "duplicate_reviewed") return `Se revisó la identidad de ${name}.`;
  if (type === "leads_merged") return `Se registró una fusión de identidad relacionada con ${name}.`;
  return `Actividad administrativa individual de ${name}.`;
}

export default async function SharedCase360Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await getAdminSessionUser();
  if (!user) redirect("/admin/login");
  const { id } = await params;
  if (!UUID.test(id)) notFound();
  const query = await searchParams;
  const detail = await getLeadGroupDetail(id);
  if (!detail) notFound();
  const q = String(Array.isArray(query.q) ? query.q[0] : query.q ?? "").trim();
  const candidates = detail.archivedAt ? [] : await searchLeadGroupCandidates(id, q);
  const mergeHistories = await Promise.all(detail.members.map((member) => getLeadMergeHistory(member.leadId)));
  const memberNames = new Map(detail.knownMembers.map((member) => [member.leadId, member.name]));
  const sharedContacts = detail.members.flatMap((left, index) => detail.members.slice(index + 1).flatMap((right) => {
    const emailMatch = left.detail.identity.email && right.detail.identity.email && left.detail.identity.email.trim().toLowerCase() === right.detail.identity.email.trim().toLowerCase();
    const phone = (value: string | null) => value?.replace(/\D/g, "") ?? "";
    const phoneMatch = phone(left.detail.identity.phone).length >= 7 && phone(left.detail.identity.phone) === phone(right.detail.identity.phone);
    return emailMatch || phoneMatch ? [{ left: left.detail.identity.name, right: right.detail.identity.name, emailMatch: Boolean(emailMatch), phoneMatch }] : [];
  }));
  const interactions = detail.members.flatMap((member) => member.detail.interactions.map((interaction) => ({ member, interaction }))).sort((a, b) => Date.parse(b.interaction.createdAt) - Date.parse(a.interaction.createdAt));
  const documents = detail.members.flatMap((member) => member.detail.documents.map((document) => ({ member, document }))).sort((a, b) => Date.parse(b.document.submittedAt) - Date.parse(a.document.submittedAt));
  const timeline = [
    ...detail.events.map((event) => ({ id: `group-${event.id}`, at: event.createdAt, copy: eventCopy(event.type, event.data, memberNames), person: null as string | null })),
    ...detail.sharedNotes.map((note) => ({ id: `case-note-${note.id}`, at: note.createdAt, copy: "Nota compartida añadida.", person: null as string | null })),
    ...detail.members.flatMap((member) => [
      ...member.detail.interactions.map((interaction) => ({ id: `form-${member.leadId}-${interaction.sourceType}-${interaction.id}`, at: interaction.createdAt, copy: `${member.detail.identity.name} completó ${interaction.sourceLabel}.`, person: member.detail.identity.name })),
      ...member.detail.notes.map((note) => ({ id: `note-${member.leadId}-${note.id}`, at: note.createdAt, copy: "Nota individual añadida.", person: member.detail.identity.name })),
      ...member.detail.managementEvents.map((event) => ({ id: `management-${member.leadId}-${event.id}`, at: event.createdAt, copy: memberManagementCopy(event.type, member.detail.identity.name), person: member.detail.identity.name })),
    ]),
    ...detail.members.flatMap((member, index) => mergeHistories[index].map((merge) => ({ id: `merge-${member.leadId}-${merge.id}`, at: merge.createdAt, copy: `Historial de fusión relacionado con ${member.detail.identity.name}.`, person: member.detail.identity.name }))),
  ].sort((a, b) => Date.parse(b.at) - Date.parse(a.at));
  const lastActivity = timeline[0]?.at ?? detail.updatedAt;
  const ok = String(Array.isArray(query.ok) ? query.ok[0] : query.ok ?? "");
  const failed = query.group_result === "rolled_back" || query.group_result === "invalid";
  return <AdminPageShell>
    <AdminPageHeader
      actions={<><Link className="btn-primary" href="/admin/leads/seguimientos">Seguimientos</Link><Link className="btn-secondary" href="/admin/leads">Volver a Leads</Link></>}
      breadcrumbs={[{ href: "/admin", label: "Admin" }, { href: "/admin/leads", label: "Leads" }, { label: "Caso compartido" }]}
      description={`${detail.members.length} personas · Última actividad ${formatDate(lastActivity)}`}
      eyebrow="Lead 360 · Caso compartido" title={detail.title}
    />
    {ok && <div className="rounded-2xl border border-emerald-300 bg-emerald-50 px-5 py-4 text-sm font-semibold text-emerald-900" role="status">{ok}</div>}
    {failed && <div className="rounded-2xl border border-red-300 bg-red-50 px-5 py-4 text-sm text-red-900" role="alert">No se pudo completar la acción. Ningún cambio fue aplicado.</div>}
    <section className="surface-card p-5 md:p-6"><div className="flex items-center gap-3"><UsersRound className="h-5 w-5 text-[#11518b]" /><h2 className="text-xl font-semibold">Resumen del caso</h2></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div><dt className="text-xs font-semibold uppercase text-[#6b7280]">Tipo</dt><dd className="mt-1 font-semibold">Caso compartido</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7280]">Estado</dt><dd className="mt-1">{LEAD_GROUP_STATUS_LABELS[detail.status]}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7280]">Seguimiento</dt><dd className="mt-1">{formatDate(detail.nextFollowUpAt)}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7280]">Propiedad principal</dt><dd className="mt-1 break-words">{detail.primaryProperty?.title ?? "Sin propiedad principal"}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7280]">Última actividad</dt><dd className="mt-1">{formatDate(lastActivity)}</dd></div></dl></section>
    <section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Personas del caso</h2><div className="mt-5 grid min-w-0 gap-4 lg:grid-cols-2">{detail.members.map((member) => <article className="min-w-0 rounded-3xl border border-[#e8e8e8] p-5" key={member.leadId}><div className="flex flex-wrap justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold">{member.detail.identity.name}</h3><p className="mt-1 break-all text-sm">{member.detail.identity.email ?? "Sin correo"}</p><p className="mt-1 text-sm">{member.detail.identity.phone ?? "Sin teléfono"}</p></div>{member.isPrimaryContact && <span className="h-fit rounded-full bg-[#d4af37]/20 px-3 py-1 text-xs font-semibold">Contacto principal</span>}</div><p className="mt-3 text-sm font-semibold">{LEAD_GROUP_ROLE_LABELS[member.role]}</p><Link className="mt-4 inline-flex text-sm font-semibold text-[#11518b] hover:underline" href={`/admin/leads/${member.leadId}`}>Abrir Lead 360 individual</Link>{!detail.archivedAt && <div className="mt-4 grid gap-3 border-t border-[#eeeeee] pt-4"><form action={updateLeadGroupMemberRoleAction} className="flex min-w-0 flex-col gap-2 sm:flex-row"><input name="group_id" type="hidden" value={id}/><input name="lead_id" type="hidden" value={member.leadId}/><input name="operation_key" type="hidden" value={randomUUID()}/><select aria-label={`Función de ${member.detail.identity.name}`} className="input-field min-w-0 flex-1" defaultValue={member.role} name="role">{Object.entries(LEAD_GROUP_ROLE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="btn-secondary" type="submit">Cambiar función</button></form>{!member.isPrimaryContact && <form action={changeLeadGroupPrimaryContactAction}><input name="group_id" type="hidden" value={id}/><input name="lead_id" type="hidden" value={member.leadId}/><input name="operation_key" type="hidden" value={randomUUID()}/><button className="btn-secondary w-full" type="submit">Hacer contacto principal</button></form>}{detail.members.length > 2 && !member.isPrimaryContact && <form action={removeLeadGroupMemberAction}><input name="group_id" type="hidden" value={id}/><input name="lead_id" type="hidden" value={member.leadId}/><input name="operation_key" type="hidden" value={randomUUID()}/><button className="btn-secondary w-full" type="submit">Remover del caso</button></form>}</div>}</article>)}</div></section>
    {sharedContacts.length > 0 && <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5 md:p-6"><h2 className="text-xl font-semibold text-amber-950">Contactos compartidos</h2><p className="mt-2 text-sm text-amber-900">Compartir datos de contacto no fusiona identidades. Estas personas permanecen separadas.</p><ul className="mt-4 grid gap-2">{sharedContacts.map((match) => <li className="rounded-2xl bg-white p-4 text-sm" key={`${match.left}-${match.right}`}><span className="font-semibold">{match.left} y {match.right}</span> · {[match.emailMatch ? "correo" : "", match.phoneMatch ? "teléfono" : ""].filter(Boolean).join(" y ")}</li>)}</ul></section>}
    <section className="surface-card p-5 md:p-6"><div className="flex items-center gap-3"><FileText className="h-5 w-5 text-[#11518b]"/><h2 className="text-xl font-semibold">Formularios exactamente como fueron enviados</h2></div><p className="mt-2 text-sm text-[#4d4d4d]">Cada respuesta permanece atribuida a la persona que completó el formulario.</p><div className="mt-5 grid min-w-0 gap-4">{interactions.length ? interactions.map(({ member, interaction }) => <LeadInteractionCard interaction={interaction} key={`${member.leadId}-${interaction.sourceType}-${interaction.id}`} submitterName={member.detail.identity.name}/>) : <p className="rounded-2xl bg-[#f8f8f8] p-4 text-sm">No hay formularios persistidos.</p>}</div></section>
    <section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Propiedades relacionadas</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{[...new Map(interactions.filter(({ interaction }) => interaction.propertyId && interaction.propertyTitle).map(({ interaction }) => [interaction.propertyId, { title: interaction.propertyTitle, slug: interaction.propertySlug, people: interactions.filter((item) => item.interaction.propertyId === interaction.propertyId).map((item) => item.member.detail.identity.name) }])).values()].map((property) => <article className="rounded-2xl border border-[#e8e8e8] p-4" key={property.slug ?? property.title}><h3 className="break-words font-semibold">{property.title}</h3><p className="mt-2 break-words text-sm text-[#4d4d4d]">Personas: {[...new Set(property.people)].join(", ")}</p>{property.slug && <Link className="mt-3 inline-flex text-sm font-semibold text-[#11518b] hover:underline" href={`/listados/${property.slug}`} target="_blank">Ver propiedad</Link>}</article>)}</div></section>
    <section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Documentos</h2><p className="mt-2 text-sm text-[#4d4d4d]">Acceso privado reutilizando la autorización de cada Lead 360 individual.</p><div className="mt-5 grid min-w-0 gap-4">{documents.length ? documents.map(({ member, document }) => <LeadDocumentCard document={document} key={`${member.leadId}-${document.source}-${document.submissionId}`} ownerId={member.leadId} ownerName={member.detail.identity.name}/>) : <p className="rounded-2xl bg-[#f8f8f8] p-4 text-sm">No hay documentos persistidos.</p>}</div></section>
    <section className="surface-card p-5 md:p-6"><div className="flex items-center gap-3"><CalendarClock className="h-5 w-5 text-[#11518b]"/><h2 className="text-xl font-semibold">Cronología combinada</h2></div><ol className="mt-5 grid gap-3">{timeline.map((event) => <li className="min-w-0 rounded-2xl border border-[#e8e8e8] p-4" key={event.id}><p className="break-words text-sm font-semibold">{event.copy}</p>{event.person && <p className="mt-1 text-xs text-[#11518b]">Persona: {event.person}</p>}<time className="mt-1 block text-xs text-[#6b7280]" dateTime={event.at}>{formatDate(event.at)}</time></li>)}</ol></section>
    <section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Estado de correos</h2><p className="mt-2 text-sm text-[#4d4d4d]">Resumen por identidad; no se mezclan destinatarios ni entregas.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{detail.members.map((member) => <article className="rounded-2xl border border-[#e8e8e8] p-4" key={member.leadId}><h3 className="font-semibold">{member.detail.identity.name}</h3>{member.detail.emailSummary.length ? <ul className="mt-3 grid gap-2 text-sm">{member.detail.emailSummary.map((summary) => <li className="flex flex-wrap justify-between gap-2" key={summary.status}><span>{summary.status}</span><span className="font-semibold">{summary.count}</span></li>)}</ul> : <p className="mt-2 text-sm text-[#6b7280]">Sin actividad de correo vinculada.</p>}</article>)}</div></section>
    <div className="grid min-w-0 gap-6 xl:grid-cols-2"><section className="surface-card p-5 md:p-6"><div className="flex items-center gap-3"><MessageSquareText className="h-5 w-5 text-[#11518b]"/><h2 className="text-xl font-semibold">Notas del caso</h2></div><p className="mt-2 text-sm text-[#4d4d4d]">Aplican al proceso compartido. No reemplazan las notas individuales.</p>{!detail.archivedAt && <form action={addLeadGroupNoteAction} className="mt-4 grid gap-3"><input name="group_id" type="hidden" value={id}/><input name="operation_key" type="hidden" value={randomUUID()}/><textarea className="input-field min-h-28 w-full" maxLength={5000} name="body" required/><button className="btn-primary" type="submit">Guardar nota compartida</button></form>}<div className="mt-5 grid gap-3">{detail.sharedNotes.map((note) => <article className="rounded-2xl bg-[#f8f8f8] p-4" key={note.id}><p className="whitespace-pre-wrap break-words text-sm">{note.body}</p><p className="mt-2 text-xs text-[#6b7280]">{note.authorUsername} · {formatDate(note.createdAt)}</p></article>)}</div></section><section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Notas individuales</h2><p className="mt-2 text-sm text-[#4d4d4d]">Permanecen vinculadas exclusivamente a cada identidad.</p><div className="mt-5 grid gap-4">{detail.members.map((member) => <div className="rounded-2xl border border-[#e8e8e8] p-4" key={member.leadId}><h3 className="font-semibold">{member.detail.identity.name}</h3>{member.detail.notes.length ? member.detail.notes.map((note) => <div className="mt-3 border-t border-[#eeeeee] pt-3" key={note.id}><p className="whitespace-pre-wrap break-words text-sm">{note.body}</p><p className="mt-1 text-xs text-[#6b7280]">{formatDate(note.createdAt)}</p></div>) : <p className="mt-2 text-sm text-[#6b7280]">Sin notas individuales.</p>}</div>)}</div></section></div>
    <section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Controles operacionales del caso</h2><p className="mt-2 text-sm text-[#4d4d4d]">El seguimiento del caso tiene prioridad en la vista operacional; los seguimientos personales siguen visibles en cada Lead 360.</p><div className="mt-5 grid min-w-0 gap-4 lg:grid-cols-3"><form action={updateLeadGroupAction} className="grid gap-2"><input name="group_id" type="hidden" value={id}/><input name="operation_key" type="hidden" value={randomUUID()}/><input name="intent" type="hidden" value="status"/><label className="text-sm font-semibold" htmlFor="case-status">Estado</label><select className="input-field" defaultValue={detail.status} id="case-status" name="status">{Object.entries(LEAD_GROUP_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="btn-secondary" type="submit">{detail.archivedAt ? "Reabrir caso" : "Actualizar estado"}</button></form>{!detail.archivedAt && <><form action={updateLeadGroupAction} className="grid gap-2"><input name="group_id" type="hidden" value={id}/><input name="operation_key" type="hidden" value={randomUUID()}/><input name="intent" type="hidden" value="follow_up"/><label className="text-sm font-semibold" htmlFor="case-follow-up">Próximo seguimiento</label><input className="input-field" defaultValue={localValue(detail.nextFollowUpAt)} id="case-follow-up" name="next_follow_up_at" type="datetime-local"/><button className="btn-secondary" type="submit">Guardar seguimiento</button></form><form action={updateLeadGroupAction} className="flex items-end"><input name="group_id" type="hidden" value={id}/><input name="operation_key" type="hidden" value={randomUUID()}/><input name="intent" type="hidden" value="contacted"/><button className="btn-secondary w-full" type="submit">Marcar como contactado</button></form></>}</div></section>
    {!detail.archivedAt && <section className="surface-card p-5 md:p-6"><h2 className="text-xl font-semibold">Añadir persona relacionada</h2><p className="mt-2 text-sm text-[#4d4d4d]">Solo se ofrecen personas con una relación confirmada con algún miembro del caso.</p><form action={`/admin/leads/casos/${id}`} className="mt-4 flex min-w-0 flex-col gap-3 sm:flex-row" method="get"><input className="input-field min-w-0 flex-1" defaultValue={q} name="q" placeholder="Nombre, correo o teléfono"/><button className="btn-secondary" type="submit">Buscar</button></form><div className="mt-4 grid min-w-0 gap-3">{candidates.map((candidate) => <form action={addLeadGroupMemberAction} className="grid min-w-0 gap-3 rounded-2xl border border-[#e8e8e8] p-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,260px)_auto] lg:items-end" key={candidate.id}><input name="group_id" type="hidden" value={id}/><input name="lead_id" type="hidden" value={candidate.id}/><input name="operation_key" type="hidden" value={randomUUID()}/><div className="min-w-0"><p className="break-words font-semibold">{candidate.name}</p><p className="break-all text-sm text-[#6b7280]">{candidate.email ?? candidate.phone ?? "Sin contacto"}</p></div><select className="input-field min-w-0" name="role">{Object.entries(LEAD_GROUP_ROLE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="btn-primary" type="submit">Añadir</button></form>)}</div></section>}
  </AdminPageShell>;
}
