import { DocumentAccessButtons } from "@/components/admin/DocumentAccessButtons";
import { LEAD_DOCUMENT_STATE_LABELS, formatDocumentSize, type Lead360Document } from "@/lib/admin/queries/lead-documents";

function formatDate(value: string) {
  return new Intl.DateTimeFormat("es-PR", { timeZone: "America/Puerto_Rico", dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}

export function LeadDocumentCard({ document, ownerId, ownerName }: { document: Lead360Document; ownerId: string; ownerName?: string }) {
  const baseHref = `/admin/leads/${ownerId}/documents/${document.source}/${document.submissionId}`;
  const tone = { available: "bg-emerald-50 text-emerald-800 border-emerald-200", pending: "bg-amber-50 text-amber-900 border-amber-200", failed: "bg-red-50 text-red-800 border-red-200", metadata_incomplete: "bg-slate-100 text-slate-700 border-slate-200" }[document.state];
  return <article className="min-w-0 rounded-3xl border border-[#e8e8e8] p-4 md:p-5"><div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="break-words font-semibold">{document.categoryLabel}</h3><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${tone}`}>{LEAD_DOCUMENT_STATE_LABELS[document.state]}</span></div><p className="mt-2 break-all text-sm font-medium text-[#334155]">{document.originalName ?? "Nombre de archivo no disponible"}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-5">{ownerName && <div><dt className="text-xs font-semibold uppercase tracking-[0.1em] text-[#6b7280]">Persona</dt><dd className="mt-1 break-words">{ownerName}</dd></div>}<div><dt className="text-xs font-semibold uppercase tracking-[0.1em] text-[#6b7280]">Fuente</dt><dd className="mt-1">{document.sourceLabel}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-[0.1em] text-[#6b7280]">Propiedad</dt><dd className="mt-1 break-words">{document.propertyTitle ?? "Sin propiedad asociada"}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-[0.1em] text-[#6b7280]">Enviado</dt><dd className="mt-1">{formatDate(document.submittedAt)}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-[0.1em] text-[#6b7280]">Formato y tamaño</dt><dd className="mt-1 break-words">{document.contentType ?? "Tipo no disponible"} · {formatDocumentSize(document.sizeBytes)}</dd></div></dl></div><div className="min-w-0 lg:max-w-64">{document.state === "available" ? <DocumentAccessButtons downloadHref={`${baseHref}?mode=download`} previewHref={document.previewable ? `${baseHref}?mode=preview` : null} /> : <p className="rounded-2xl bg-[#f8f8f8] p-3 text-sm text-[#4d4d4d]">No hay acceso disponible en este estado.</p>}</div></div></article>;
}
